name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  bake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - uses: adambirds/docker-compose-action@v1.5.0
      with:
        compose-file: "./docker/docker-compose.yml"
        up-flags: "--build"
        down-flags: "--volumes"
